stages:
  - build
  - deploy

variables:
  BUILD_DIR: $CI_PROJECT_DIR/build

image: node

build:desktop:
  stage: build
  only:
      - master
      - develop
  script:
    - cp -r . /var/lib/desktop
    - cd /var/lib/desktop
    - npm install -g gulp bower
    - npm install
    - bower install
    - gulp build --mode=production
    - mkdir -p $BUILD_DIR/desktop
    - cp -r ./dist/production/* $BUILD_DIR/desktop
    - cp .local-web-server.json $BUILD_DIR/desktop
    - mkdir -p $BUILD_DIR/bin
    - cp -r ./bin/* $BUILD_DIR/bin
    - find . -type f -not -name \*.html -exec rm -rf {} \;
    - find . -type d -empty -delete
    - rm -rf ./src/index.html
    - cp -r ./src/* $BUILD_DIR/desktop

  artifacts:
    untracked: true
    expire_in: 1 hour


build:mobile:
  stage: build
  only:
      - master
      - develop
  script:
    - mkdir -p /var/lib/mobile
    - cd /var/lib/mobile
    - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoftware.com/nested/web-mobile-app.git .
    - git checkout master
    - npm install -g yarn
    - npm install
    - npm run build:prod
    - mkdir -p $BUILD_DIR/mobile
    - cp ./package.json $BUILD_DIR/mobile
    - cp -r ./node_modules $BUILD_DIR/mobile
    - cp -r ./src $BUILD_DIR/mobile
    - cp -r ./build $BUILD_DIR/mobile/build
  artifacts:
    untracked: true
    expire_in: 1 hour

deploy:production:
  image: gitlab/dind
  stage: deploy
  only:
    - master
  services:
    - docker:dind
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
  dependencies:
    - build:mobile
    - build:desktop


deploy:develop:
  image: gitlab/dind
  stage: deploy
  only:
    - develop
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "dev"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - build:mobile
    - build:desktop


deploy:business:
  image: gitlab/dind
  stage: deploy
  only:
    - business
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "business"
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
