stages:
  - build
  - deploy

variables:
  BUILD_DIR: $CI_PROJECT_DIR/build

image: "registry.ronaksoftware.com/base/node:builder"

build:desktop:
  stage: build
  only:
      - master
      - develop
  script:
    - cp -a ./. /var/lib/desktop
    - cd /var/lib/desktop
    - ls ./node_modules
    - apk add --update python build-base
    - npm install -g bower
    - npm install
    - bower install
    - cp -f ./modified_components/* ./bower_components/
    - npm rebuild node-sass
    - ./node_modules/.bin/gulp build --mode=production --ver=$CI_PIPELINE_ID
    - mkdir -p $BUILD_DIR/webapp
    - mkdir -p $BUILD_DIR/webapp/t
    - mkdir -p $BUILD_DIR/webapp/oauth
    - cp -a ./bin/token/. $BUILD_DIR/webapp/t/
    - cp -a ./bin/oauth/. $BUILD_DIR/webapp/oauth/
    - cp -r ./dist/production/* $BUILD_DIR/webapp
    - cp ./lws.config.js $BUILD_DIR/webapp
    - mkdir -p $BUILD_DIR/bin
    - cp -a ./bin/. $BUILD_DIR/bin
    - find . -type f -not -name \*.html -not -name print.css -exec rm -rf {} \;
    - rm -rf ./src/index.html
    - cp -a ./src/. $BUILD_DIR/webapp

  artifacts:
    untracked: true
    expire_in: 1 hour


build:mobile:
  stage: build
  only:
      - master
      - develop
  script:
    - mkdir -p /var/lib/mobile-org
    - cd /var/lib/mobile-org
    - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoftware.com/nested/web-mobile-app.git .
    - git checkout master
    - cp -a ./. /var/lib/mobile
    - cd /var/lib/mobile
    - npm install
    - npm run build:prod
    - mkdir -p $BUILD_DIR/webapp/m
    - cp -a ./build/m $BUILD_DIR/webapp
  artifacts:
    untracked: true
    expire_in: 1 hour

build:admin:
  stage: build
  image: theotherjim/node-gulp-jspm
  only:
    - master
    - develop
  script:
    - mkdir -p /var/lib/admin
    - cd /var/lib/admin
    - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoftware.com/nested/web-admin.git .
    - git fetch origin feature/nginx
    - git checkout feature/nginx
    - npm install
    - jspm install
    - ./node_modules/.bin/gulp build
    - mkdir -p $BUILD_DIR/webapp/admin
    - cp -r ./dist/* $BUILD_DIR/webapp/admin

  artifacts:
    untracked: true
    expire_in: 1 hour

deploy:production:
  image: gitlab/dind
  stage: deploy
  only:
    - master
  services:
    - docker:dind
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
  dependencies:
    - build:mobile
    - build:desktop
    - build:admin


deploy:develop:
  image: gitlab/dind
  stage: deploy
  only:
    - develop
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "dev"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - build:mobile
    - build:desktop
    - build:admin


deploy:business:
  image: gitlab/dind
  stage: deploy
  only:
    - business
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "business"
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
