stages:
  - build
  - deploy

variables:
  BUILD_DIR: $CI_PROJECT_DIR/build

image: "node:8-alpine"

build:desktop:
  stage: build
  only:
      - master
      - develop
  script:
    - cp -a ./. /var/lib/desktop
    - cd /var/lib/desktop
    - apk add --update python build-base git
    - npm install -g bower
    - npm install
    - bower install
    - cp -fR ./modified_components/* ./bower_components/
    - npm rebuild node-sass
    - ./node_modules/.bin/gulp build --mode=production --ver=$CI_PIPELINE_ID
    - mkdir -p $BUILD_DIR/webapp
    - mkdir -p $BUILD_DIR/webapp/t
    - mkdir -p $BUILD_DIR/webapp/oauth
    - mkdir -p $BUILD_DIR/webapp/firebase
    - cp -a ./bin/token/. $BUILD_DIR/webapp/t/
    - cp -a ./bin/oauth/. $BUILD_DIR/webapp/oauth/
    - cp -a ./bin/firebase/. $BUILD_DIR/webapp/firebase/
    - cp ./bin/firebase/firebase-messaging-sw.js $BUILD_DIR/webapp/
    - cp -r ./dist/production/* $BUILD_DIR/webapp
    - cp ./lws.config.js $BUILD_DIR/webapp
    - mkdir -p $BUILD_DIR/bin
    - cp -a ./bin/. $BUILD_DIR/bin
    - find . -type f -not -name \*.html -not -name print.css -exec rm -rf {} \;
    - rm -rf ./src/index.html
    - cp -a ./src/. $BUILD_DIR/webapp

  artifacts:
    untracked: true
    expire_in: 1 hour


build:mobile:
  stage: build
  image: "node:10-alpine"
  only:
      - master
      - develop
  script:
    - apk add --update python build-base git
    - mkdir -p /var/lib/mobile-org
    - cd /var/lib/mobile-org
    - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoft.com/nested/legacy/web-mobile-app.git .
    - git checkout master
    - cp -a ./. /var/lib/mobile
    - cd /var/lib/mobile
    - npm install
    - npm run build:prod
    - mkdir -p $BUILD_DIR/webapp/m
    - cp -a ./build/m $BUILD_DIR/webapp
  artifacts:
    untracked: true
    expire_in: 1 hour



build:admin:
  stage: build
  image: node:12-alpine
  only:
    - master
  script:
    - mkdir -p /var/lib/oldadmin
    - apk update && apk upgrade && apk add --no-cache bash git openssh
    - cd /var/lib/oldadmin
    - git clone --single-branch --branch old http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoft.com/nested/legacy/web-admin.git .
    - mkdir -p $BUILD_DIR/webapp/oldadmin
    - cp -r ./dist/* $BUILD_DIR/webapp/oldadmin
    - mkdir -p /var/lib/admin
    - cd /var/lib/admin
    - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoft.com/nested/legacy/web-admin.git .
    - npm install
    - PUBLIC_URL=/admin ./node_modules/.bin/react-scripts build
    - mkdir -p $BUILD_DIR/webapp/admin
    - cp -r ./build/* $BUILD_DIR/webapp/admin
# build old admin
#   script:
#     - mkdir -p /var/lib/oldadmin
#     - npm install gulp -g
#     - npm install jspm -g
#     - apk update && apk upgrade && apk add --no-cache bash git openssh
#     - cd /var/lib/oldadmin
#     - git clone http://gitlab-ci-token:$CI_BUILD_TOKEN@git.ronaksoftware.com/nested/web-admin.git .
#     - npm install
#     - jspm install
#     - ./node_modules/.bin/gulp build
#     - mkdir -p $BUILD_DIR/webapp/oldadmin
#     - cp -r ./dist/* $BUILD_DIR/webapp/oldadmin

  artifacts:
    untracked: true
    expire_in: 1 hour

deploy:production:
  image: gitlab/dind
  stage: deploy
  only:
    - master
  services:
    - docker:dind
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$TAG .
    - docker push $CI_REGISTRY_IMAGE:$TAG
  dependencies:
    - build:mobile
    - build:desktop
    - build:admin


deploy:develop:
  image: gitlab/dind
  stage: deploy
  only:
    - develop
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "dev"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ls ./build/webapp
    - docker build --pull -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - build:mobile
    - build:desktop
    - build:admin


deploy:business:
  image: gitlab/dind
  stage: deploy
  only:
    - business
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "business"
  script:
    - export TAG=`git describe --abbrev=0 --tags`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$TAG
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - build:mobile
    - build:desktop
    - build:admin