dev:
    image: registry.ronaksoftware.com/nested/web-app:0.0.1-dev
    working_dir: /usr/src/app-dev
    restart: none
    volumes:
      - ".:/usr/src/app-dev"
    ports:
      - "3002:3002"
    command: bin/run.staging.sh

